name: pr2changelog
on:
    pull_request:
        branches:
            - master
        types: [closed]

jobs:
    generate:
        if: github.event.pull_request.merged == true

        name: changelog generator
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Generate changelog
              uses: corp-0/pr2changelog@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  repo: ${{ github.repository }}
                  pr_number: ${{ github.event.pull_request.number }}
